// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutLineHUMG.Models;

namespace OutLineHUMG.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210422044117_Subject")]
    partial class Subject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OutLineHUMG.Models.Specialized", b =>
                {
                    b.Property<int>("Idspecialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeSpecialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contentspecialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseofYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Statusspecialized")
                        .HasColumnType("tinyint");

                    b.Property<string>("Titlespecialized")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idspecialized");

                    b.ToTable("specialized");
                });

            modelBuilder.Entity("OutLineHUMG.Models.Subject", b =>
                {
                    b.Property<int>("Idsubject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idspecialized")
                        .HasColumnType("int");

                    b.Property<byte>("StatusSubject")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleSubject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idsubject");

                    b.HasIndex("Idspecialized");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("OutLineHUMG.Models.Subject", b =>
                {
                    b.HasOne("OutLineHUMG.Models.Specialized", "Specialized")
                        .WithMany()
                        .HasForeignKey("Idspecialized")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialized");
                });
#pragma warning restore 612, 618
        }
    }
}
